#!/usr/bin/env bash
docker_image="vell001/ubt18.04_ros_xrdp:latest"

docker_name="ubt18.04_ros_xrdp"
num=$(docker ps -a | grep -w ${docker_name} | wc -l)
if [ $num -ne 0 ]; then
  container_id=$(docker ps -a | grep -w ${docker_name} | grep -v grep | awk '{print $1}')
  echo "use old container: "$container_id
  docker container start $container_id
  docker exec -d $container_id /bin/start_xrdp
else
  docker run -it \
    --privileged=true \
    --hostname="$(hostname)" \
    --publish="23389:3389/tcp" \
    --name=${docker_name} \
    -v /data:/data \
    --shm-size="2g" \
    ${docker_image} /bin/bash
fi
